[phases.setup]
nixPkgs = [
  "python39",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "fontconfig",
  "glib",
  "gobject-introspection",
  "pkg-config"
]

[phases.install]
dependsOn = ["setup"]

[start]
cmd = "python main.py"