[phases.setup]
nixPkgs = ["python39"]
aptPkgs = [
    "chromium",
    "libgobject-2.0-0",
    "libcairo2",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    "shared-mime-info",
    "fonts-liberation",
    "libharfbuzz0b",
    "libjpeg62-turbo",
    "libpng16-16"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pip install weasyprint>=60.0",
    "playwright install chromium --with-deps"
]

[start]
cmd = "python main.py"