[phases.setup]
nixPkgs = [
  "python39",
  "cairo",
  "pango",
  "gdk-pixbuf", 
  "fontconfig",
  "glib",
  "gobject-introspection",
  "pkg-config",
  "freetype",
  "libffi",
  "gtk3",
  "gobject-introspection-dev"
]

[phases.build]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "/app"