[phases.setup]
nixPkgs = [
  "python39",
  "cairo",
  "pango",
  "gdk-pixbuf", 
  "fontconfig",
  "freetype",
  "glib",
  "gobject-introspection"
]

[phases.install]
dependsOn = ["setup"]

[start]
cmd = "python main.py"