[phases.setup]
nixPkgs = [
  "python39",
  "cairo",
  "pango", 
  "gdk-pixbuf",
  "libffi",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "fribidi",
  "librsvg",
  "glib",
  "gtk3",
  "wkhtmltopdf"
]

[phases.install]
dependsOn = ["setup"]

[start]
cmd = "python main.py"