[phases.setup]
nixPkgs = ["python39", "chromium"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pip install weasyprint>=60.0 cairocffi>=1.6.0",
    "playwright install chromium --with-deps"
]

[start]
cmd = "python main.py"